### ISSUE TITLE
Some gateways incorrectly reported as offline

### ISSUE THREAD

**Issue by hybla0** [ipfs/public-gateway-checker#127]
Some gateways, for example ipfs.mttk.net, are reported as offline but instead they are online right now

**Comment by jessicaschilling** [comment]
Thanks, @hybla0 - happened to jump on a few minutes after your post and I'm seeing ipfs.mttk.net as online. This may not be the easiest thing to diagnose - wondering if you were just experiencing a timeout since resolved?
If you experience any other large-scale incorrect "offline" messages, please post in this issue. Will leave open for a while to keep an eye on the situation.

**Comment by hsanjuan** [comment]
@hybla0 , the connection check is performed directly from your computer, so this might be a connection issue from your location.

**Comment by hybla0** [comment]
@hsanjuan thanks for clarifying that, i am not much knowledgeable I web development tech.

Anyway some gateways are dead: they no more resolve like ipfs.ink, ipfs.busy.org
