### ISSUE TITLE
feat: finalize metrics modal and icon

### ISSUE THREAD

**Issue by lidel** [ipfs/public-gateway-checker#340]
The cookie button introduced in #309 is placed in a very unfortunate, prominent place.
It looks like an important item related to gateway checks:

> ![2022-12-06_13-17](https://user-images.githubusercontent.com/157609/205910630-529370c7-a209-4439-9f93-72fa004b44a9.png)

An easy fix would be to move it to top bar, we already have github icon there:

>  ![2022-12-06_13-24](https://user-images.githubusercontent.com/157609/205911768-201df7d8-4de6-48c3-a528-ea7eb2c8086e.png)

**Comment by SgtPooki** [comment]
@juliaxbow @whizzzkid  what do you think? I placed it where it is to purposefully get folks attention :) but i figured these issues would come!

I originally wanted it in the top right; theres previous patterns on sites to place it in the bottom right, and there's reasons against all places we could put it without a global site configuration gear or something.

For sites/apps unlike webui/desktop where we dont have a config/settings page we'll need a standard for where it goes. This should be a blocker for ipfs/ipfs-gui#105

**Comment by juliaxbow** [comment]
+1 to moving it away from its current location where it looks like it's related to reading the gateway checker. While i'm not opposed to including it in the menu, in the absence of a footer (due to infinite scroll/loading of gateways) I think our best options are:

1) Including a line of text explaining current settings and a link to change/opt out of current selection. 
<img width="864" alt="Screen Shot 2022-12-07 at 12 38 58 AM" src="https://user-images.githubusercontent.com/58958327/206097539-ca2fe0a1-28db-4dbf-82c0-5512482f274e.png">

2) A widget in a fixed position on the bottom left or right hand of the page. It would look something like:
https://user-images.githubusercontent.com/58958327/206096978-26bb1a75-a8d0-4548-a6ca-b7aa8fc84647.mov

>For sites/apps unlike webui/desktop where we dont have a config/settings page we'll need a standard for where it goes. This should be a blocker for https://github.com/ipfs/ipfs-gui/issues/105
@SgtPooki agreed, and also given the convo today around default opt-in we'll need to update the language and selection options. Will look at this in a few hours

**Comment by juliaxbow** [comment]
Circling back. If we move towards the floating cookie icon, I suggest we do shift to a modal box vs banner as previously proposed.  This also addresses #341. By clicking on the cookie icon, users can opt out of non-necessary metric collection and click a link to learn more about what information we're collecting. If we have a privacy policy (I don't think one exists yet) we should link to that as well. 

Note: As we're still defining necessary vs non-necessary metrics (https://github.com/ipfs/ipfs-gui/issues/125) toggles in the prototype below are generic "All Cookies" vs "Strictly Necessary" but this can be changed once we've determined categories. In the prototype below, users would need to click "How we use cookies" to determine what falls under strictly necessary.

LMK if we want to go in this direction and I will send over design specs.

https://user-images.githubusercontent.com/58958327/207742019-03f62380-e584-4aee-89b8-bb55080864b1.mov

**Comment by SgtPooki** [comment]
> in the absence of a footer (due to infinite scroll/loading of gateways)

We could still fix the header to the bottom of the viewport even with infinite scrolling, but I like the new design (continue below)

> As we're still defining necessary vs non-necessary metrics

I think we've got a strong signal and precedence (thanks to @lidel's comment at https://github.com/ipfs/ipfs-gui/issues/125#issuecomment-1352295236) that allowing users to opt out of metrics (for now) is a good step forward.

If we decide that users should not be able to opt-out in the future (due to lacking metrics we need to make decisions) we can update the necessary metrics toggle to be disabled. I think one great point from lidel is that many users may not care, but we should get a good signal on that. 

Speaking of, I've just added a sub-task in https://github.com/ipfs-shipyard/ignite-metrics/issues/2 for this

> LMK if we want to go in this direction and I will send over design specs.

@juliaxbow I like the new design. I propose the following to address item 4 from "Current planned solution" in https://github.com/ipfs/ipfs-gui/issues/125:

1. Modal is open by default for users who have never seen it. (new & existing users will get this)
    * Closing via X or "close" button will update consent according to toggles selected
2. Toggles are enabled by default 
3. "how we use cookies" could be rephrased to be "See more about our telemetry collection" or similar
    * Link should lead users to https://github.com/ipfs/ipfs-gui/issues/125 or notion page documenting process and history of the metrics decisions behind the new modal and cookie logo
5. rephrase "your cookie settings" description to be more generic for all projects.

**Comment by SgtPooki** [comment]
Note that I updated issue description in ipfs/ipfs-gui#125. @juliaxbow could we get a mock up of displaying all the toggles for features listed under "Metrics distinctions". i.e. the features listed at https://support.count.ly/hc/en-us/articles/360037441932-Web-analytics-JavaScript-#features-for-consent

I imagine we will need some expanding config of some sort so the initial banner isn't annoyingly huge. Can we have an expandable section in the modal that allows for toggling individual items on/off? or at least four toggles to represent the groupings in ipfs/ipfs-gui#125? i.e. 
```
const necessaryFeatures = ['sessions', 'views']
const marketingFeatures = ['attribution', 'users', 'location']
const performanceFeatures = ['events', 'crashes', 'apm']
const trackingFeatures = ['scrolls', 'clicks', 'forms', 'star-rating', 'feedback']
```

also, we should probably update the "necessary" toggle to say "minimum" or something.

**Comment by juliaxbow** [comment]
> "how we use cookies" could be rephrased to be "See more about our telemetry collection" or similar
- I changed to "our cookie and metrics collection policy" to keep consistent but can change if you feel strongly. Will look for other wording.

> rephrase "your cookie settings" description to be more generic for all projects.
- What other projects are you referring to? Could do "manage metric collection" but that might be confusing to change terminology for users since we have a cookie button. 

```
const necessaryFeatures = ['sessions', 'views']
const marketingFeatures = ['attribution', 'users', 'location']
const performanceFeatures = ['events', 'crashes', 'apm']
const trackingFeatures = ['scrolls', 'clicks', 'forms', 'star-rating', 'feedback']
```
- QQ Did you categorize these or is that from Countly? 
- Are you tied to the naming convention here? Wonder if "marketing" is a misnomer for what we're seeking here. 
- Included a dropdown in the prototype below but that will lead to a whole lot of toggles. I think we should group and limit choices, at least for some categories that are are less desired by us.

![Cookie Modal](https://user-images.githubusercontent.com/58958327/208221279-144c85be-c420-463f-bf56-a87d91862478.png)


[Cookie Modal.pdf](https://github.com/ipfs/public-gateway-checker/files/10250647/Cookie.Modal.pdf)

**Comment by SgtPooki** [comment]
> > "how we use cookies" could be rephrased to be "See more about our telemetry collection" or similar
> 
> * I changed to "our cookie and metrics collection policy" to keep consistent but can change if you feel strongly. Will look for other wording.

I think the term "cookie" is what is throwing me off. We don't technically use cookies at all by default; see https://support.count.ly/hc/en-us/articles/360037441932-Web-analytics-JavaScript-#sdk-data-storage. So "telemetry collection" is the most generic while being more factually correct. There are a number of callouts here:

1. We don't want to scare folks off by saying we are using cookies when we're not
2. we don't want to lie to users about storing data on their devices (they really don't care about the difference between cookies and local storage, do they?) https://law.stackexchange.com/questions/30739/do-the-gdpr-and-cookie-law-regulations-apply-to-localstorage is a decent read on this, though a little obtuse.

We don't use cookies and don't store user data, but the term "cookie" will immediately imply some sort of "user data storage." I would prefer we do not use the term cookie at all.

> > rephrase "your cookie settings" description to be more generic for all projects.
> 
> * What other projects are you referring to? Could do "manage metric collection" but that might be confusing to change terminology for users since we have a cookie button.

All of our projects. Ideally, the messaging we use should be consistent across ipfs-webui, ipfs-desktop, ipfs-companion, and all others listed at https://github.com/ipfs/ipfs-gui/issues/105

I agree that the cookie button is confusing if we're not using cookies. Do you have an idea for another icon to indicate metrics collection? Maybe we don't use an icon at all, but a floating "metrics collection settings" text, or even a gear icon?

We should update this sooner than later.

> ```
> const necessaryFeatures = ['sessions', 'views']
> const marketingFeatures = ['attribution', 'users', 'location']
> const performanceFeatures = ['events', 'crashes', 'apm']
> const trackingFeatures = ['scrolls', 'clicks', 'forms', 'star-rating', 'feedback']
> ```
> 
> * QQ Did you categorize these or is that from Countly?

The strings ('sessions', 'views', etc..) are countly features. the groupings ('marketing', 'performance', etc..) are my own categorization of those features.

> * Are you tied to the naming convention here? Wonder if "marketing" is a misnomer for what we're seeking here.

We could re-categorize those if you think the countly features belong in a different group. See the descriptions at https://support.count.ly/hc/en-us/articles/360037441932-Web-analytics-JavaScript-#features-for-consent

> * Included a dropdown in the prototype below but that will lead to a whole lot of toggles. I think we should group and limit choices, at least for some categories that are are less desired by us.

Thanks for throwing that together. Ok I totally agree.. limiting them to the groupings would be a lot less confusing and more simple to implement. Sounds like we need to do an audit of our groupings.

**Comment by juliaxbow** [comment]
Thanks for the clarification re: our use (or lack thereof) of cookies. Makes sense and I'll play around with alternatives today. 

Re: Standardizing language
- I'll take on updating the language (for this issue and to align across ipfs-gui). 
- QQ - Did legal get back with the privacy policy? I can steal verbiage from that, which is probably our best source of truth

**Comment by SgtPooki** [comment]
Thanks!

> QQ - Did legal get back with the privacy policy? I can steal verbiage from that, which is probably our best source of truth

I meet with legal on Thursday the 5th at 9:30am PST to discuss privacy policy updates and creating a more generic privacy policy for all of our projects

**Comment by SgtPooki** [comment]
> happy to make changes to design if you have feedback

I think the modal design you have, without the granular control, is going to be the best route moving forward.

### i.e. Don't expand like this:
![image](https://user-images.githubusercontent.com/1173416/210440149-2c1ea8bb-f9b8-498f-bfc3-3d088241a4cb.png)

### Leave like this:
![image](https://user-images.githubusercontent.com/1173416/210440232-c69d1cdc-3a98-41f2-a930-5ed605d22b8b.png)


So we could probably remove the borders, and the carrot icons

**Comment by juliaxbow** [comment]
**Design**
- Removed the dropdown and updated the design slightly ([Figma file](https://www.figma.com/file/lB6Jby1QCTLMhVG0x7TqFW/IPFS-Design-Work?node-id=867%3A13625&t=vNYbdpLZWpkfzB7c-0) & screenshots below)
- New preferences window
![New Metric Consent Toggles (2)](https://user-images.githubusercontent.com/58958327/210648397-5152eece-86a6-45dd-8812-c9b6ae6464ca.png)

**Button options**
- Agreed we should move away from the cookie icon since it's an inaccurate representation of what we're actually collecting. 
- Option 1: Keep the floating icon in the bottom left, update with "metrics" icon. This is less intrusive but may not be as intuitive for users upon first viewing

https://user-images.githubusercontent.com/58958327/210647575-1000f9cc-dd73-430e-941a-a1421bccd827.mov



- Option 2: Change to a floating button with text in the bottom right. This may block some gateway content but is explicit as to what action the user can expect. In this version, clicking on the button would bring the modal to the center of the page vs corner

https://user-images.githubusercontent.com/58958327/210647553-38154410-0409-4ba9-b887-8b7d05dec3fd.mov


Flow (With hover metrics button)
![Prototype Redline](https://user-images.githubusercontent.com/58958327/210647981-d6849eed-b1f0-480c-a0f9-9ef4de605f1f.png)


**Verbiage**
- Addressing content in notion [here](https://www.notion.so/pl-strflt/Metrics-Collection-and-Consent-Language-0d4059f11d4d474bb76d00539d778d8d)

**Comment by SgtPooki** [comment]
@juliaxbow I really like the metrics icon, and I love the text in option 2. I think a mix of 1 and 2 where the icon used in option 2 is on the left would be great.

**Comment by SgtPooki** [comment]
@juliaxbow this issue was assigned to you, so I still left you on it, but I also assigned Dan because he's working on it now. Do you still need to have this assigned to you?

**Comment by SgtPooki** [comment]
We will be adding multiple toggles later, if not now, so I would prefer to keep the UI designed with that in mind

**Comment by juliaxbow** [comment]
>I think a mix of 1 and 2 where the icon used in option 2 is on the left would be great.

could also have it expand on hover, like:

https://user-images.githubusercontent.com/58958327/210923127-63e7c6c2-0f33-4196-b3be-64708c93fcbc.mov

**Comment by SgtPooki** [comment]
I really like that one @juliaxbow
