### ISSUE TITLE
Move cookie prompt to the bottom

### ISSUE THREAD

**Issue by lidel** [ipfs/public-gateway-checker#341]
The cookie prompt introduced in https://github.com/ipfs/public-gateway-checker/pull/309 is pushing page contents down, causing reflow when user submits the choice.

Would it be ok to move it down, and have it fixed to the bottom of viewport? This way we dont have reflow:

>  ![2022-12-06_13-25](https://user-images.githubusercontent.com/157609/205912214-77fe23a9-4a0a-492b-9045-f455692ab88a.png)

**Comment by SgtPooki** [comment]
I'm fine with moving to the bottom as a fixed element in the viewport.

**Comment by davidfcopozo** [comment]
Hello, I'll be more than happy to contribute to this. Can it be assigned to me?

**Comment by juliaxbow** [comment]
This conversation is strongly related to #340 where we're discussing a floating, fixed cookie button in the bottom left corner. If we do this, suggest that we not have any banner and instead shift to a modal box. OK with a bottom banner while that's being discussed, though, to fix the reflow issue!

**Comment by davidfcopozo** [comment]
I just read the conversation and I like the new modal, it's a way better approach than the current banner, but if it's not an immediate solution I think that moving it to the bottom in the meantime is a good idea since the current banner at the top is not even fixed, and users can easily lose sight of if while scrolling.
