### ISSUE TITLE
Add support for custom test hash

### ISSUE THREAD

**Issue by KonoromiHimaries** [ipfs/public-gateway-checker#54]
example
```
https://ipfs.github.io/public-gateway-checker/Qmaisz6NMhDB51cCvNWa1GMS7LU1pAxdF4Ld6Ft9kZEP2a<-custom-hash-here
```

**Comment by koalalorenzo** [comment]
What is the use case? Can't you use any IPFS gateway?

**Comment by jamiew** [comment]
I also don't understand the use case, especially for a public checker

**Comment by andrasfuchs** [comment]
I think it would be useful in a case where the default gateway times out for a particular ipfs or ipns hash.

I'm in a situation where I use a VPN service and I can't open a particular IPNS and I don't really know if that's because I got the wrong hash or because I'm behind the VPN and something else goes wrong along the way.

It would be great to have the opportunity to test both IPFS and IPNS hashes with this checker.

**Comment by jamiew** [comment]
Got it. This would be a pretty easy patch, except for the content-matching, since we wouldn't know what the underlying hash is supposed to contain. Would happily accept a PR

**Comment by andrasfuchs** [comment]
I created a pull request for this, please test it if you can: https://github.com/ipfs/public-gateway-checker/pull/64

**Comment by andrasfuchs** [comment]
@jamiew Could you spare some time to look at the PR?

**Comment by jamiew** [comment]
Sorry, just coming up for air. Commenting on the PR

**Comment by jessicaschilling** [comment]
Closing as stale, but please feel free to re-open if needed.
